development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "b1a12a6092e700e422118e2a44b7928327d03b674fd40f7d7f0babc6c84ad4bc"
  signature_expiration: 3600 # one hour
