# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb1ec8bcc00d8eaf67badb0ad9eaacdabd46fba118a5218fff87506c036790551306886b80f14ea98bd5e1c4530c6cadc07059ebb9d965caadedf6b22ce51c4d
  facebook_app_id: 205623189786000
  facebook_app_secret: 8b785910fffe9bf07288a2186b92f3dd
test:
  secret_key_base: f8bac263ca6801905f8b5f1ad2a8865797651448b81f29dad54f721ef297a1b3533e5bc02eefe2b0fa4d8606ae13d8b312c5117c55a209064521ec50bd34b853

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
